const questions = [
    {
        level: 1,
        name: "隅の死活第１型",
        hp: 2,
        steps: [
            [
                "         ",
                "         ",
                "         ",
                "         ",
                "      B  ",
                "       B ",
                "    BBBWW",
                "    BWWW ",
                "    BW N ",
            ],[
                "         ",
                "         ",
                "         ",
                "         ",
                "      B  ",
                "       B ",
                "    BBBWW",
                "    BWWW ",
                "    BW B ",
            ]
        ]
    },
    {
        level: 1,
        name: "隅の死活第4型",
        hp: 2,
        steps: [
            [
                "         ",
                "         ",
                "         ",
                "         ",
                "      WW ",
                "      WB ",
                "    WWWB ",
                "    WBBB ",
                "        N",
            ],[
                "         ",
                "         ",
                "         ",
                "         ",
                "      WW ",
                "      WB ",
                "    WWWB ",
                "    WBBB ",
                "        B",
            ]
        ]
    },
    {
        level: 1,
        name: "隅の死活第5型",
        hp: 2,
        steps: [
            [
                "         ",
                "         ",
                "         ",
                "         ",
                "      BB ",
                "      BW ",
                "    BBBW ",
                "    BWWW ",
                "     W N ",
            ],[
                "         ",
                "         ",
                "         ",
                "         ",
                "      BB ",
                "      BWw",
                "    BBBW ",
                "    BWWWN",
                "     W B ",
            ],[
                "         ",
                "         ",
                "         ",
                "         ",
                "      BB ",
                "      BWW",
                "    BBBW ",
                "    BWWWB",
                "     W B ",
            ]
        ]
    },
    {
        level: 2,
        name: "隅の死活第6型",
        hp: 2,
        steps: [
            [
                "         ",
                "         ",
                "         ",
                "         ",
                "      B  ",
                "       B ",
                "   BBBBWW",
                "   BWWW  ",
                "       N ",
            ],[
                "         ",
                "         ",
                "         ",
                "         ",
                "      B  ",
                "       B ",
                "   BBBBWW",
                "   BWWWw ",
                "       BN",
            ],[
                "         ",
                "         ",
                "         ",
                "         ",
                "      B  ",
                "       B ",
                "   BBBBWW",
                "   BWWWW ",
                "    w NBB",
            ],[
                "         ",
                "         ",
                "         ",
                "         ",
                "      B  ",
                "       B ",
                "   BBBBWW",
                "   BWWWW ",
                "    W BBB",
            ]
        ]
    },
    {
        level: 1,
        name: "隅の死活第7型",
        hp: 2,
        steps: [
            [
                "         ",
                "         ",
                "     W   ",
                "         ",
                "     W   ",
                "      W  ",
                "    WWBB ",
                "    WB   ",
                "      N  ",
            ],[
                "         ",
                "         ",
                "     W   ",
                "         ",
                "     W   ",
                "      W  ",
                "    WWBB ",
                "    WB wN",
                "      B  ",
            ],[
                "         ",
                "         ",
                "     W   ",
                "         ",
                "     W   ",
                "      WN ",
                "    WWBB ",
                "    WB WB",
                "      Bw ",
            ],[
                "         ",
                "         ",
                "     W   ",
                "         ",
                "     W w ",
                "      WBN",
                "    WWBB ",
                "    WB WB",
                "      BW ",
            ],[
                "         ",
                "         ",
                "     W   ",
                "         ",
                "     W W ",
                "      WBB",
                "    WWBB ",
                "    WB WB",
                "      BW ",
            ]
        ]
    },
    {
        level: 2,
        name: "隅の死活第7型変化",
        hp: 2,
        steps: [
            [
                "         ",
                "         ",
                "     W   ",
                "         ",
                "     W   ",
                "      W  ",
                "    WWBB ",
                "    WB   ",
                "      N  ",
            ],[
                "         ",
                "         ",
                "     W   ",
                "         ",
                "     W   ",
                "      W  ",
                "    WWBB ",
                "    WB Nw",
                "      B  ",
            ],[
                "         ",
                "         ",
                "     W   ",
                "         ",
                "     W   ",
                "      W  ",
                "    WWBB ",
                "    WB BW",
                "    w B N",
            ],[
                "         ",
                "         ",
                "     W   ",
                "         ",
                "     W   ",
                "      W  ",
                "    WWBBN",
                "    WB BW",
                "    W Bw ",
            ],[
                "         ",
                "         ",
                "     W   ",
                "         ",
                "     W   ",
                "      W  ",
                "    WWBBB",
                "    WB BW",
                "    W BW ",
            ]
        ]
    },
    {
        level: 1,
        name: "隅の死活第8型",
        hp: 2,
        steps: [
            [
                "         ",
                "         ",
                "     B   ",
                "         ",
                "     B   ",
                "      B  ",
                "    BBWW ",
                "    BW   ",
                "     W N ",
            ],[
                "         ",
                "         ",
                "     B   ",
                "         ",
                "     B   ",
                "      B  ",
                "    BBWW ",
                "    BW w ",
                "    NW B ",
            ],[
                "         ",
                "         ",
                "     B   ",
                "         ",
                "     B   ",
                "      B  ",
                "    BBWW ",
                "    BW W ",
                "    BW B ",
            ]
        ]
    },
    {
        level: 3,
        name: "隅の死活第9型",
        hp: 2,
        steps: [
            [
                "         ",
                "         ",
                "     B   ",
                "         ",
                "     B B ",
                "      BW ",
                "    BBWW ",
                "    BW  N",
                "      W  ",
            ],[
                "         ",
                "         ",
                "     B   ",
                "         ",
                "     B B ",
                "      BW ",
                "    BBWW ",
                "    BW wB",
                "    N W  ",
            ],[
                "         ",
                "         ",
                "     B   ",
                "         ",
                "     B B ",
                "      BW ",
                "    BBWW ",
                "    BW WB",
                "    BNW w",
            ],[
                "         ",
                "         ",
                "     B   ",
                "         ",
                "     B B ",
                "      BW ",
                "    BBWW ",
                "    BW WB",
                "    BBW W",
            ]
        ]
    },
    {
        level: 1,
        name: "隅の死活第10型",
        hp: 2,
        steps: [
            [
                "         ",
                "         ",
                "     W   ",
                "         ",
                "     W   ",
                "      WN ",
                "    WWBB ",
                "    WB   ",
                "    W B  ",
            ],[
                "         ",
                "         ",
                "     W   ",
                "         ",
                "     W w ",
                "      WB ",
                "    WWBB ",
                "    WB  N",
                "    W B  ",
            ],[
                "         ",
                "         ",
                "     W   ",
                "         ",
                "     W W ",
                "      WBw",
                "    WWBB ",
                "    WB  B",
                "    W BN ",
            ],[
                "         ",
                "         ",
                "     W   ",
                "         ",
                "     W W ",
                "      WBW",
                "    WWBB ",
                "    WB  B",
                "    W BB ",
            ]
        ]
    },
    {
        level: 1,
        name: "隅の死活第11型",
        hp: 2,
        steps: [
            [
                "         ",
                "         ",
                "         ",
                "         ",
                "     W   ",
                "      WW ",
                "  W WWBB ",
                "     B N ",
                "         ",
            ],[
                "         ",
                "         ",
                "         ",
                "         ",
                "     W   ",
                "      WW ",
                "  W WWBB ",
                "    wB B ",
                "     N   ",
            ],[
                "         ",
                "         ",
                "         ",
                "         ",
                "     W   ",
                "      WW ",
                "  W WWBB ",
                "    WB B ",
                "     B   ",
            ]
        ]
    },
    {
        level: 2,
        name: "隅の死活第12型",
        hp: 2,
        steps: [
            [
                "         ",
                "         ",
                "         ",
                "         ",
                "     B   ",
                "      BB ",
                "  B BBWW ",
                "     W  N",
                "      W  ",
            ],[
                "         ",
                "         ",
                "         ",
                "         ",
                "     B   ",
                "      BB ",
                "  B BBWWN",
                "     W wB",
                "      W  ",
            ],[
                "         ",
                "         ",
                "         ",
                "         ",
                "     B   ",
                "      BB ",
                "  B BBWWB",
                "   NwW WB",
                "      W  ",
            ],[
                "         ",
                "         ",
                "         ",
                "         ",
                "     B   ",
                "      BB ",
                "  B BBWWB",
                "   BWW WB",
                "    w WN ",
            ],[
                "         ",
                "         ",
                "         ",
                "         ",
                "     B   ",
                "      BB ",
                "  B BBWWB",
                "   BWW WB",
                "    W WB ",
            ]
        ]
    },
    {
        level: 2,
        name: "隅の死活第13型",
        hp: 2,
        steps: [
            [
                "         ",
                "         ",
                "         ",
                "         ",
                "     B   ",
                "      BBB",
                "  B BBWW ",
                "     W W ",
                "       N ",
            ],[
                "         ",
                "         ",
                "         ",
                "         ",
                "     B   ",
                "      BBB",
                "  B BBWWw",
                "     W W ",
                "      NB ",
            ],[
                "         ",
                "         ",
                "         ",
                "         ",
                "     B   ",
                "      BBB",
                "  B BBWWW",
                "    NW W ",
                "      BBw",
            ],[
                "         ",
                "         ",
                "         ",
                "         ",
                "     B   ",
                "      BBB",
                "  B BBWWW",
                "    BW WN",
                "     wBBW",
            ],[
                "         ",
                "         ",
                "         ",
                "         ",
                "     B   ",
                "      BBB",
                "  B BBWWW",
                "    BW WB",
                "     WBB ",
            ]
        ]
    },
    {
        level: 2,
        name: "隅の死活第14型",
        hp: 2,
        steps: [
            [
                "         ",
                "         ",
                "         ",
                "         ",
                "     B   ",
                "      BBB",
                "  B BBWW ",
                "     WBW ",
                "      N  ",
            ],[
                "         ",
                "         ",
                "         ",
                "         ",
                "     B   ",
                "      BBB",
                "  B BBWWN",
                "     WBW ",
                "      Bw ",
            ],[
                "         ",
                "         ",
                "         ",
                "         ",
                "     B   ",
                "      BBB",
                "  B BBWWB",
                "     WBW ",
                "      BW ",
            ]
        ]
    },
    {
        level: 3,
        name: "隅の死活第15型",
        hp: 2,
        steps: [
            [
                "         ",
                "         ",
                "         ",
                "         ",
                "     B   ",
                "      BBB",
                "  B BBWW ",
                "     W  N",
                "       W ",
            ],[
                "         ",
                "         ",
                "         ",
                "         ",
                "     B   ",
                "      BBB",
                "  B BBWWw",
                "     W  B",
                "     N W ",
            ],[
                "         ",
                "         ",
                "         ",
                "         ",
                "     B   ",
                "      BBB",
                "  B BBWWW",
                "   NwW  B",
                "     B W ",
            ],[
                "         ",
                "         ",
                "         ",
                "         ",
                "     B   ",
                "      BBB",
                "  B BBWWW",
                "   BWWN B",
                "    wB W ",
            ],[
                "         ",
                "         ",
                "         ",
                "         ",
                "     B   ",
                "      BBB",
                "  B BBWWW",
                "   BWWB B",
                "    WB W ",
            ]
        ]
    },
    {
        level: 3,
        name: "隅の死活第15型変化",
        hp: 2,
        steps: [
            [
                "         ",
                "         ",
                "         ",
                "         ",
                "     B   ",
                "      BBB",
                "  B BBWW ",
                "     W  N",
                "       W ",
            ],[
                "         ",
                "         ",
                "         ",
                "         ",
                "     B   ",
                "      BBB",
                "  B BBWWw",
                "     W  B",
                "     N W ",
            ],[
                "         ",
                "         ",
                "         ",
                "         ",
                "     B   ",
                "      BBB",
                "  B BBWWW",
                "   NwW  B",
                "     B W ",
            ],[
                "         ",
                "         ",
                "         ",
                "         ",
                "     B   ",
                "      BBB",
                "  B BBWWW",
                "   BWW NB",
                "     BwW ",
            ],[
                "         ",
                "         ",
                "         ",
                "         ",
                "     B   ",
                "      BBB",
                "  B BBWWW",
                "   BWWwBB",
                "    NBWW ",
            ],[
                "         ",
                "         ",
                "         ",
                "         ",
                "     B   ",
                "      BBB",
                "  B BBWWW",
                "   BWWWBB",
                "    BBWW ",
            ]
        ]
    },
    {
        level: 2,
        name: "隅の死活第16型",
        hp: 2,
        steps: [
            [
                "         ",
                "         ",
                "         ",
                "       B ",
                "         ",
                "      BB ",
                "    BBWW ",
                "  B BW  W",
                "      WN ",
            ],[
                "         ",
                "         ",
                "         ",
                "       B ",
                "         ",
                "      BB ",
                "    BBWW ",
                "  B BW wW",
                "    N WB ",
            ],[
                "         ",
                "         ",
                "         ",
                "       B ",
                "         ",
                "      BB ",
                "    BBWW ",
                "  B BW wW",
                "    B WB ",
            ]
        ]
    },
    {
        level: 1,
        name: "隅の死活第18型",
        hp: 2,
        steps: [
            [
                "         ",
                "         ",
                "         ",
                "         ",
                "         ",
                "     BBB ",
                "   BBWW  ",
                "   BWN W ",
                "      W  ",
            ],[
                "         ",
                "         ",
                "         ",
                "         ",
                "         ",
                "     BBB ",
                "   BBWWN ",
                "   BWB W ",
                "    w W  ",
            ],[
                "         ",
                "         ",
                "         ",
                "         ",
                "         ",
                "     BBB ",
                "   BBWWB ",
                "   BWBwWN",
                "    W W  ",
            ],[
                "         ",
                "         ",
                "         ",
                "         ",
                "         ",
                "     BBB ",
                "   BBWWB ",
                "   BWBWWB",
                "    W W  ",
            ]
        ]
    },
    {
        level: 1,
        name: "隅の死活第20型",
        hp: 2,
        steps: [
            [
                "         ",
                "         ",
                "         ",
                "         ",
                "     W   ",
                "    W WW ",
                "  W WBB  ",
                "   WB  B ",
                "      N  ",
            ],[
                "         ",
                "         ",
                "         ",
                "         ",
                "     W   ",
                "    W WW ",
                "  W WBB  ",
                "   WBw B ",
                "    N B  ",
            ],[
                "         ",
                "         ",
                "         ",
                "         ",
                "     W   ",
                "    W WW ",
                "  W WBB N",
                "   WBW Bw",
                "    B B  ",
            ],[
                "         ",
                "         ",
                "         ",
                "         ",
                "     W   ",
                "    W WW ",
                "  W WBB B",
                "   WBW BW",
                "    B B  ",
            ]
        ]
    },
    {
        level: 1,
        name: "隅の死活第25型",
        hp: 2,
        steps: [
            [
                "         ",
                "         ",
                "         ",
                "         ",
                "         ",
                "    BBBBB",
                "    BWWWW",
                "    BW N ",
                "    BW   ",
            ],[
                "         ",
                "         ",
                "         ",
                "         ",
                "         ",
                "    BBBBB",
                "    BWWWW",
                "    BW BN",
                "    BW w ",
            ],[
                "         ",
                "         ",
                "         ",
                "         ",
                "         ",
                "    BBBBB",
                "    BWWWW",
                "    BW BB",
                "    BW W ",
            ]
        ]
    },
    {
        level: 1,
        name: "隅の死活第34型",
        hp: 2,
        steps: [
            [
                "         ",
                "         ",
                "         ",
                "      W  ",
                "       W ",
                "    WWWBW",
                " W  WBBB ",
                "   WBB N ",
                "         ",
            ],[
                "         ",
                "         ",
                "         ",
                "      W  ",
                "       W ",
                "    WWWBW",
                " W  WBBB ",
                "   WBB B ",
                "         ",
            ]
        ]
    },
    {
        level: 1,
        name: "隅の死活第35型",
        hp: 2,
        steps: [
            [
                "         ",
                "         ",
                "         ",
                "      W  ",
                "       W ",
                "    WWWB ",
                " W  WBBB ",
                "   WBB WN",
                "         ",
            ],[
                "         ",
                "         ",
                "         ",
                "      W  ",
                "       W ",
                "    WWWB ",
                " W  WBBB ",
                "   WBB WB",
                "      Nw ",
            ],[
                "         ",
                "         ",
                "         ",
                "      W  ",
                "       W ",
                "    WWWB ",
                " W  WBBB ",
                "   WBB WB",
                "      BW ",
            ]
        ]
    },
    {
        level: 1,
        name: "隅の死活第35型変化",
        hp: 2,
        steps: [
            [
                "         ",
                "         ",
                "         ",
                "      W  ",
                "       W ",
                "    WWWB ",
                " W  WBBB ",
                "   WBB WN",
                "         ",
            ],[
                "         ",
                "         ",
                "         ",
                "      W  ",
                "       W ",
                "    WWWB ",
                " W  WBBB ",
                "   WBBNWB",
                "      w  ",
            ],[
                "         ",
                "         ",
                "         ",
                "      W  ",
                "       W ",
                "    WWWBN",
                " W  WBBB ",
                "   WBBBWB",
                "      Ww ",
            ],[
                "         ",
                "         ",
                "         ",
                "      W  ",
                "       W ",
                "    WWWBB",
                " W  WBBB ",
                "   WBBBWB",
                "      WW ",
            ]
        ]
    },
    {
        level: 1,
        name: "隅の死活第38型",
        hp: 2,
        steps: [
            [
                "         ",
                "         ",
                "         ",
                "      W  ",
                "       W ",
                "    WWWB ",
                "  W WBBB ",
                "   WB  N ",
                "   W B W ",
            ],[
                "         ",
                "         ",
                "         ",
                "      W  ",
                "       W ",
                "    WWWBw",
                "  W WBBB ",
                "   WB  B ",
                "   W BNW ",
            ],[
                "         ",
                "         ",
                "         ",
                "      W  ",
                "       W ",
                "    WWWBW",
                "  W WBBB ",
                "   WBw B ",
                "   W BBWN",
            ],[
                "         ",
                "         ",
                "         ",
                "      W  ",
                "       W ",
                "    WWWBW",
                "  W WBBB ",
                "   WBW B ",
                "   W BB B",
            ]
        ]
    },
    {
        level: 1,
        name: "隅の死活第44型",
        hp: 2,
        steps: [
            [
                "         ",
                "         ",
                "         ",
                "         ",
                "     W   ",
                "      WW ",
                "   WWWBB ",
                "   WBB N ",
                "         ",
            ],[
                "         ",
                "         ",
                "         ",
                "         ",
                "     W   ",
                "      WW ",
                "   WWWBB ",
                "   WBB B ",
                "         ",
            ]
        ]
    },
    {
        level: 1,
        name: "辺の死活第10型",
        hp: 2,
        steps: [
            [
                "         ",
                "         ",
                "         ",
                "         ",
                "         ",
                "   WWW   ",
                " WWBBBWW ",
                " WB   BW ",
                "  N   B  ",
            ],[
                "         ",
                "         ",
                "         ",
                "         ",
                "         ",
                "   WWW   ",
                " WWBBBWW ",
                " WB   BW ",
                "  B   B  ",
            ]
        ]
    },
    {
        level: 1,
        name: "辺の死活第13型",
        hp: 2,
        steps: [
            [
                "         ",
                "         ",
                "         ",
                "         ",
                "         ",
                "   BBB   ",
                "BBBWWWBB ",
                "  W   WB ",
                "    N W  ",
            ],[
                "         ",
                "         ",
                "         ",
                "         ",
                "         ",
                "   BBB   ",
                "BBBWWWBB ",
                "  W  NWB ",
                "   wB W  ",
            ],[
                "         ",
                "         ",
                "         ",
                "         ",
                "         ",
                "   BBB   ",
                "BBBWWWBB ",
                "  W  BWB ",
                "   WB W  ",
            ]
        ]
    },
    {
        level: 1,
        name: "辺の死活第13型変化",
        hp: 2,
        steps: [
            [
                "         ",
                "         ",
                "         ",
                "         ",
                "         ",
                "   BBB   ",
                "BBBWWWBB ",
                "  W   WB ",
                "    N W  ",
            ],[
                "         ",
                "         ",
                "         ",
                "         ",
                "         ",
                "   BBB   ",
                "BBBWWWBB ",
                "  W w WB ",
                "   NB W  ",
            ],[
                "         ",
                "         ",
                "         ",
                "         ",
                "         ",
                "   BBB   ",
                "BBBWWWBB ",
                "  W W WB ",
                "  wBBNW  ",
            ],[
                "         ",
                "         ",
                "         ",
                "         ",
                "         ",
                "   BBB   ",
                "BBBWWWBB ",
                "  W W WB ",
                "  WBBBW  ",
            ]
        ]
    },
];
